---
name: Checking pull request

on:
  pull_request:
    

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Executing tests for pull request
        run: |
          echo  "Running tests for pull request "${{ github.event.pull_request.title }}"
          
      - name: Checkout
        uses: actions/checkout@v4

