---
name: Deploy to production - Mitigated

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy, e.g. 1.2.3'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Execute deployment script
        id: execute
        env:
          VERSION: ${{ github.event.inputs.version }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          ./deploy.sh "$VERSION"
