---
name: Checking pull request - Mitigated

on:
  pull_request:
    
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Executing tests for pull request
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo Running tests for pull request "$PR_TITLE"

      - name: Checkout
        uses: actions/checkout@v4
